#!/bin/sh
## nvram wrapper

useage()
{
	echo "nvram show"
	echo "nvram commit"
	echo "nvram get key"
	echo "nvram set key='val'"
	echo "nvram unset key"
}

#echo "nvram: $*, parnum: $#" >&2

case $# in
	0)	useage
		exit 0;
	;;
	1)
		case $1 in
			"show")
				ralink_init show 2860
			;;
			"commit")
				#nothing to do, auto commit when set
				nvram_set 2860 commit "`date '+%Y-%m-%d %H:%M:%S'`"
			;;
			*) useage;;
		esac
	;;
	2)
		case $1 in
			"get")
				nvram_get $2
			;;
			"set")
				KEY=`echo $2| awk -F= '{print $1}'`
				VAL=`echo $2| awk -F= '{print $2}'`
				nvram_set $KEY $VAL
				#echo "nvram set $KEY $VAL" >&2
			;;
			"unset")
				nvram_set $2 #set empty
			;;
		esac
	;;
	*) 
		useage
		exit 0;
	;;
esac
