#!/bin/sh

LOG()
{
	echo $1 >> /var/tmp/startup.log
}

ERR()
{
	LOG "error:"$*
	return 1
}

init_sysfs()
{
	#fstab mount
	mount -a
	
	#auto mount failed
	mkdir -p /dev/pts
	mount -t devpts none /dev/pts
	
	mkdir /var/cache
	mkdir /var/empty
	mkdir /var/lib
	mkdir /var/lib/arpd
	mkdir /var/lib/misc
	mkdir /var/lib/pcmcia
	mkdir /var/lock
	mkdir /var/log
	mkdir /var/pcmcia
	mkdir /var/run
	mkdir /var/spool
	mkdir /var/tmp
	mkdir /var/www
}

init_jffs2()
{
	EBLOCK=`mtdinfo /dev/mtd5 | grep Amount | awk '{print $4}'`

	umount /jffs2 || ERR "unmount jffs2.";

	flash_erase -j /dev/mtd5 0 ${EBLOCK} || ERR "flash_erase failed.";

	mount -t jffs2 /dev/mtdblock5 /jffs2 || ERR "mount block5 failed.";

	cp -a /etc /jffs2 || ERR "cp etc";
	cp -a /ugw /jffs2 || ERR "cp ugw";

	LOG "init_jffs2 finished";
}

mount_jffs2()
{
	mkdir -p /jffs2
	if ! mount -t jffs2 /dev/mtdblock5 /jffs2  || ! [ -e /jffs2/ugw ] || ! [ -e /jffs2/etc ]; then
		init_jffs2
	else
		LOG "recover files after upgrade..."
		ugw_coverup.sh >> /var/tmp/startup.log
	fi
	mount -o,rbind /jffs2/ugw	/ugw
	mount -o,rbind /jffs2/etc	/etc
}

#start base system
export PATH=/ugw/bin:/ugw/scripts:/bin:/sbin:/usr/bin:/usr/sbin:$PATH
export LD_LIBRARY_PATH=/ugw/so:/usr/lib:/lib

#init sysfs
init_sysfs

#监测按键,停止系统
press_any_key && exit 0

#开启网口,供调试
insmod /lib/modules/ralink_wdt.ko
insmod /lib/modules/rt_rdm.ko
insmod /lib/modules/raeth.ko
ifconfig lo 127.0.0.1

#配置好交换机
config-vlan.sh 3 0
ifconfig eth2 up
ifconfig eth2 192.168.1.110

#for telnet debugging
telnetd

#mount jffs2, ugw & etc
mount_jffs2

#start daemons
ugw.sh &

#Banner
cat /etc/motd